dataset: prep3
size: 100000
variability_runs: 10
time_cutoff: 3650
overallpath: /yourpath
seed: 6
preprocessing_seed: TRUE
encode_seed: TRUE
latent_seed: FALSE
survival_seed: TRUE
with_nores: False
store_surv_models: True
reduced_run: True
reduce_proteomics: False
one_latent: FALSE
letter: VL